---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/auth/login":
    post:
      summary: login authentication
      tags:
      - Authentication
      security: []
      parameters: []
      responses:
        '200':
          description: successful
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
  "/api/v1/converter/cidr_to_mask":
    post:
      summary: Convert CIDR to mask
      tags:
      - Converters
      security:
      - bearerAuth: {}
      parameters: []
      responses:
        '200':
          description: CIDR converted to mask
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cidr:
                  type: string
              required:
              - cidr
  "/api/v1/converter/mask_to_cidr":
    post:
      summary: Convert Mask to Cidr
      tags:
      - Converters
      security:
      - bearerAuth: {}
      parameters: []
      responses:
        '200':
          description: Mask converted to CIDR
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mask:
                  type: string
              required:
              - mask
  "/api/v1/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      tags:
      - Users
      security:
      - bearerAuth: {}
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - username
              - password
              - password_confirmation
servers:
- url: http://localhost:3000
- url: http://terraform-infra-elb-sre-app-848223682.us-east-1.elb.amazonaws.com
components:
  securitySchemes:
    bearerAuth:
      description: Bearer token authentication
      type: http
      scheme: bearer
      bearerFormat: JWT
      name: Authorization
      in: header
security:
- bearerAuth: []
