name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          SENTRY_KEY: ${{ secrets.SENTRY_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.TAGS }}
          secrets: |
            "DB_USER= ${{ env.DB_USER }}"
            "DB_PASSWORD= ${{ env.DB_PASSWORD }}"
            "DB_HOST= ${{ env.DB_HOST }}"
            "SENTRY_KEY= ${{ env.SENTRY_KEY }}"
            "JWT_SECRET= ${{ env.JWT_SECRET }}"      
